{% set name = "aws_lambda_builders" %}
{% set version = "1.59.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d863db6b6fcf1377bd6e4b2eb5443874b839ffa65d4cde2b531c8c2120bd99e3

build:
  noarch: python
  number: 0
  entry_points:
    - lambda-builders=aws_lambda_builders.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - setuptools
    - six >=1.11,<2
    - wheel

test:
  imports:
    - aws_lambda_builders
    - aws_lambda_builders.workflows
    - aws_lambda_builders.workflows.custom_make
    - aws_lambda_builders.workflows.dotnet_clipackage
    - aws_lambda_builders.workflows.go_modules
    - aws_lambda_builders.workflows.java
    - aws_lambda_builders.workflows.java_gradle
    - aws_lambda_builders.workflows.java_maven
    - aws_lambda_builders.workflows.nodejs_npm
    - aws_lambda_builders.workflows.nodejs_npm_esbuild
    - aws_lambda_builders.workflows.python_pip
    - aws_lambda_builders.workflows.ruby_bundler
    - aws_lambda_builders.workflows.rust_cargo

about:
  home: https://github.com/awslabs/aws-lambda-builders
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python library to compile, build & package AWS Lambda functions for several runtimes & frameworks.
  dev_url: https://github.com/awslabs/aws-lambda-builders

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
